apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: game-server-dev
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: game_traffic_listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 22222
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: tcp_proxy
                    cluster: k8s_statefulset_game_server

      clusters:
        - name: k8s_statefulset_game_server
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: k8s_statefulset_game_server
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: bullet-hell-server-0.bullet-hell-server-headless.game-server-dev.svc.cluster.local
                          port_value: 22222
                  - endpoint:
                      address:
                        socket_address:
                          address: bullet-hell-server-1.bullet-hell-server-headless.game-server-dev.svc.cluster.local
                          port_value: 22222
                  - endpoint:
                      address:
                        socket_address:
                          address: bullet-hell-server-2.bullet-hell-server-headless.game-server-dev.svc.cluster.local
                          port_value: 22222
