apiVersion: v1
kind: Service
metadata:
  name: envoy-loadbalancer
  namespace: game-server-dev
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.9
  selector:
    app: envoy
  ports:
    - name: tcp
      protocol: TCP
      port: 22222
      targetPort: 22222
