apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: metallb-system
  name: metallb-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
      component: controller
  template:
    metadata:
      labels:
        app: metallb
        component: controller
    spec:
      # serviceAccountName: metallb-controller
      containers:
        - name: controller
          image: metallb/controller:v0.13.10
          args:
            - --port=7472
            - --config=/etc/metallb/config/config
          ports:
            - name: webhook
              containerPort: 7472
          volumeMounts:
            - name: config
              mountPath: /etc/metallb/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7472
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 7472
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: metallb-config
